name: clean_arch_template
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.6.1
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  pretty_dio_logger: ^1.4.0
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  sqflite: ^2.4.2
  dartz: ^0.10.1
  envied: ^1.1.1
  path_provider: ^2.1.5
  objectbox: ^4.2.0
  objectbox_flutter_libs: any
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.5.0
  json_serializable: ^6.8.0
  envied_generator: ^1.1.1
  riverpod_generator: ^2.6.5
  objectbox_generator: any

flutter:
  uses-material-design: true

scripts: derry.yaml
